version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: mmcode_wordpress
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: mmcode_wp
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.5
    container_name: mmcode_db
    restart: always
    environment:
      MYSQL_DATABASE: mmcode_wp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mmcode_db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: mmcode_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: password
      PMA_PORT: 3306
    depends_on:
      - db

volumes:
  mmcode_db_data:
